// export const apiUrl = 'http://localhost:8080/api/v1'
// export const imageUrl = 'http://localhost:8080/image'
export const apiUrl = 'https://food-blog-services.onrender.com/api/v1'
export const imageUrl = 'https://food-blog-services.onrender.com/image'
export const LOCAL_STORAGE_TOKEN_NAME = 'token'